counts:
  count:
    beacon_model: numTotalResults

#------------------------------------------------------------------------------#

filtering_terms:
  id:
    beacon_model: id
  label:
    beacon_model: label
  type:
    beacon_model: type
  scopes:
    beacon_model: scopes

#------------------------------------------------------------------------------#

biosamples:
  biosample_id:
    beacon_model: id
  
  individual_id:
    beacon_model: individualId

  biosample_status:
    beacon_model: biosampleStatus

  sample_origin_type:
    beacon_model: sampleOriginType
    
  histological_diagnosis:      
    beacon_model: histologicalDiagnosis
  
  sampled_tissue:
    beacon_model: sampleOriginDetail
  
  pathological_stage:
    beacon_model: pathologicalStage
               
  tnm:
    beacon_model: pathologicalTnmFindings
   
  tumor_grade:
    beacon_model: tumorGrade

  age_iso:
    beacon_model: collectionMoment

  info:
    beacon_model: info

  notes:
    beacon_model: notes

  # bycon specials 
  
  icdo_morphology:
    bycon_defined: icdoMorphology
  
  icdo_topography:
    bycon_defined: icdoTopography
  
  external_references:
    bycon_defined: externalReferences

  analysis_info:
    bycon_defined: analysisInfo

  cohorts:
    bycon_defined: cohorts

  geo_location:
    bycon_defined: geoLocation

  updated:
    bycon_defined: updated
    
#------------------------------------------------------------------------------#

individuals:

  individual_id:
    beacon_model: id
 
  sex:
    beacon_model: sex

  age_iso:
    beacon_model: diseases.onset.age
  
  histological_diagnosis_id:
    beacon_model: diseases.diseaseCode.id

  histological_diagnosis_label:
    beacon_model: diseases.diseaseCode.label
  
  followup_time:
    beacon_model: diseases.followupTime

  followup_state_id:
    beacon_model: diseases.followupState.id
  
  followup_state_label:
    beacon_model: diseases.followupState.label

  diseases_notes:
    beacon_model: diseases.notes

  info:
    beacon_model: info

  # bycon specials

  updated:
    bycon_defined: updated

#------------------------------------------------------------------------------#

analyses:
  analysis_id:
    beacon_model: id
      
  biosample_id:
    beacon_model: biosampleId

  individual_id:
    beacon_model: individualId 
  
  calling_pipeline:
    beacon_model: pipelineName

  analysis_info: 
    bycon_defined: analysisInfo   
  
  platform:
    bycon_defined: platformModel     
       
  updated:
    bycon_defined: updated
     
#------------------------------------------------------------------------------#

g_variants:
  variant_id:
    beacon_model: caseLevelData.variantId

  analysis_id:
    beacon_model: caseLevelData.analysisId
  
  biosample_id:
    beacon_model: caseLevelData.biosampleId
  
  individual_id:
    beacon_model: caseLevelData.individualId

  variant_internal_id:
    beacon_model: variantInternalId

  variation_location:
    beacon_model: variation.location

  variant_copychange:
    beacon_model: variation.copyChange

  identifiers:
    beacon_model: identifiers

  molecularAttributes:
    beacon_model: molecularAttributes
